linters:
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused
  disable:
    # deprecated linters
    - deadcode
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    # disabled due to personal preference
    - depguard
    - dupword
    - exhaustruct
    - gomnd
    - nlreturn
    - tagliatelle
    - unparam
    - varnamelen
    - wrapcheck
    - wsl
    # disabled because of generics. https://github.com/golangci/golangci-lint/issues/2649
    - rowserrcheck
    - sqlclosecheck
    - wastedassign
    # TODO
    - goconst

linters-settings:
  cyclop:
    max-complexity: 26
  funlen:
    lines: 100
    statements: 100
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/sapslaj/)
      - blank
      - dot
    custom-order: true
  nestif:
    min-complexity: 8

issues:
  exclude:
    - Line contains TODO/BUG/FIXME # godox
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - exhaustive
        - forcetypeassert
        - funlen
    - path: ui
      linters:
        - ireturn # returning an interface is intended behavior for bubbletea
    - path: ui/styles.go
      linters:
        - gochecknoglobals # globals allowed for lipgloss styles
    - path: main\.go
      linters:
        - forbidigo
